# Generated by Django 3.2 on 2022-01-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220114_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogimages'),
        ),
    ]
