# Generated by Django 3.2 on 2022-01-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
