# Generated by Django 3.2 on 2022-01-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
